var array_as_words_love=[
	// '一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十',
	'一直都觉得很幸运，世界这么大，能与你相遇相知',
	'其实你并不是什么都好，但是你什么都让我忘不了',
	'无论我本人多么平庸，我总觉得对你的爱很美',
	'我做事三分钟热度，却也爱你这么久',
	'每次想起你，我都发现自己是微笑着的',
	'陪伴是最长情的告白，相守是最浪漫的承诺',
	'让我们一直牵着手，告诉对方什么是永远',
	'我上辈子可能是碳酸饮料，一见到你就开心的冒泡',
	'你是年少的欢喜，倒过来念也是你',
	'你的心，是我去到世界尽头还想再回来的地方',
	'虽非青梅竹马，却也两情相悦，得一城终老，携一人白首',
	'想做你的牙齿，我难受的时候，有你疼',
	'我希望我80岁醒来的时候，是你在我身边…',
	'我真是个大笨蛋，除了喜欢你，我什么都做不好',
	'我希望，我的孩子笑起来，有你的模样',
	'山有木兮木有枝，心悦君兮君不知',
	'你是我这一生等了半世未拆的礼物',
	'我一直都没有换电话，就是等你找我',
	'不是除了你，我就没人要；只是除了你，我谁都不要',
	'纵然有百万个理由离开你，我也会找一个理由为你留下',
	'你是我的四月蒹葭，爱恋依然苍苍',
	'以前错过的风景，今后我们一起去看',
	'和你在一起的时候，我就没羡慕过别人',
	'愿有岁月可回头，且以深情共白首',
	'好不容易遇见你，竟花光了我所有运气',
	'都怪你让我分心。从遇见你的那一刻，你就让我分心',
	'不好意思，有些情话是我学的，但爱你是真心的',
	'你累不累？你在我脑海里跑了一天了',
	'我不喜欢这个世界，我只喜欢你',
	'谢命运让你我相遇，于千万人之中，在时光的荒野里，不早也不晚',
	'你的过去，我来不及参与。你的将来，我奉陪到底',
	'春林初盛，春水初生，春风十里，不如你',
	'任他凡事清浊，为你一笑间轮回甘堕',
	'愿用我三生烟火，换你一世迷离',
	'只缘感君一回顾，使我思君朝与暮',
	'待我长发及腰，少年娶我可好。待你青丝绾正，铺十里红妆可愿',
	'秒回不是碰巧，而是我一直在等你的消息',
	'我有点花心，爱上了每一个你',
	'我本想浪荡一生，却不小心钟情你一人',
	'鸟患了恐高症，鱼变成了旱鸭子，所有逻辑都被推翻，我还是要喜欢你',
	'遇见你是多小的概率我不知道，我只想把失去你的概率变为零',
	// '一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十',
	'我能想到最浪漫的事，就是和你一起慢慢变老',
	'你一定是偷偷作弊了，不然在我心里怎么可能会是满分',
	'不是因为想恋爱才遇见你，而是遇见你之后我才有了恋爱的想法',
	'你就像是开着一架喷气式的小飞机，扑哧扑哧地就飞进了我的心',
	'不做玫瑰，要做你心上野草，一点湿意便肆意疯长，烧不尽吹又生',			
	'无人问津的渡口总是开满野花，就像我爱你却支支吾吾说不出话',
	'这世间虽有千般好，但唯有你最珍贵',
	'我不喜欢迁就，却用最干净的真心，为你妥协了很久',
	'时光明媚了你的眼，也让你住进了我的心房',
	'你不是最好的，但是有你，却比什么都好',
	'没什么特别喜欢的零食，没什么特别喜欢的歌，唯有个特别喜欢的你',
	'我还是很喜欢你，像风走了八千里，不问归期',
	'我还是很喜欢你，像长空过雁，字字相思',
	'还是很喜欢你，像燕尾剪断烟雨，不知何起',
	'我目光短浅，只看得见你，我心胸狭窄，只容得下你',
	'山川草原湖泊，不及你的双眸深谭动人；世间万般美好，不及你对我轻轻一笑',
	'最长的情，是平淡中的不离不弃，最贴心的的暖，是风雨中的相依相伴',
	'我曾把光阴浪费，甚至鲁莽得视死如归，因为爱上了你，才开始渴望长命百岁',
	'往后余生，风雪是你，平淡是你，心底温柔是你，目光所致都是你',
	'我想用余生为你暖一盏茶，微风扬起时，勿忘归家',
	'我也想知道，你究竟是哪里好，竟让我如何也忘不掉',
	'只因为我喜欢你，那一刻，这世上便不再有逻辑',
	'最美丽的事，莫过于在最好的时光遇见你，相互嫌弃，却又不离不弃',
	'我曾爱慕诗与远方，无所羁绊，直到遇见了你，才发现你的心才是我想去的地方',
	'在爱你这件事上，我的眼睛、耳朵、嘴巴统统都是同谋',
	'这种心跳的喜欢，就是我帮你写个名字，都会觉得荣幸万分',
	'想要惯得你无法无天，宠得你娇俏任性。我做过最好的事，就是爱上了你',
	'早就想劝你别吸烟，但烟雾中的你又是那么帅',
	'我希望我知道如何戒掉你',
	'一辈子只面对一个人，想想就可怕，但如果是眼前这个人的话，愿意赌一下',
	'水中月是天上月，眼前人是心上人',
	'来日方长，给你朝朝，夕夕也给你',
	'我攒了一辈子的情话，想要说给你听',
	'承蒙你的出现，够我喜欢好多年',
	'岁月安然，不负遇见；不偏不倚，刚好是你',
	'我知道遇见你不容易，错过会很可惜，我不希望余生都是回忆，我想余生每天都是你，我爱你',
	'我不爱听那些浮夸的情话，可对我而言，你说的每一句都是情话',
	'我希望，以后你能用我的名字拒绝所有人',
	'你是我的可遇不可求。我可以不吃饭不睡觉，但无法不想你',
	'在我流淌的时光里，只有一个你。我喜欢你，没有技巧，真诚且野蛮',
	'其他女生又漂亮又温柔又懂事，但是那关我什么事，我最喜欢的就只有你',
	'我的酒量大概就是2打啤酒，或者半斤白酒，再或者你的一次微笑吧',
	'我喜欢那些闪光的东西，比如冬日的雪花，天上的星星，还有你的眼睛',
	'时间是外在的光斑，还是心跳微妙的浮点，而你的微笑百看不腻，像阳光柔和干净',
	'我愿把因果轮回还给僧尼，把眉目清秀还给天地，把松间细雨还给初遇，把一见钟情还给你',
	'我对你是指针向南，我爱你是深海沉船，你一来是万物复苏，你离开是世界荒芜',
	'遇见你花了我十多年的时间，爱上你却只用了几秒种',
	'也许你并不是为我而生，可我却有幸与你相伴',
	'遇见你是偶然的，喜欢你是自然的，爱上你是毅然的，得到你是欣然的，伴你一生是必然的',
	// '一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十',
];



var array_as_words_birthday=[
	'愿你所有等待都能出现，所有愿望都能实现，所有期待都能如愿，所有梦想都能兑现，愿你生日快乐无限',
	'今天是你生日，送你一块蛋糕，愿你吃出纯真美丽；歌曲也送给你，愿你听出吉祥如意！生日快乐',
	'蛋糕一切满嘴油，相见匆匆别匆匆。日历一翻365，流星一闪划长空。生日快乐，愿你心想事成借东风',
	'祝你百事可乐，万事芬达，天天哇哈哈，月月乐百事，年年高乐高，心情似雪碧，永远都醒目',
	'摘一颗星，采一朵云，装入思念的礼包，将一份宁静和喜悦悄悄带给你，愿你青春长驻，生日快乐',
	'送你一份温馨两份问候，三份美好四份祝福，五份高贵六份前程，七份典雅八份柔情，九份财运十份真诚',
	'老实说我是上帝赐给你的礼物，但愿这份礼物不是太糟糕，希望你能特别喜欢这个礼物，祝你生日快乐',
	'你生日到了？我差点忘记！都怪岁月没在你脸上留下痕迹，沧桑没在你的气质上打折扣。生日快乐哦',
	'零点零分零一秒，我的祝福刚刚好，昨夜星辰昨夜梦，今日许愿今日圆。生日快乐哦',
	'开心快乐一锅同煮，吉祥如意一船同渡，平安顺利一起上路，幸福好运一同奔赴。生日快乐哦',
	'今天是个特别的日子，我在月宫里看到你。真是猪性不改，怎么又跑到月宫来了？呵呵，猪你生日快乐',
	'猪你快快长！猪你早日出栏！猪你生日快乐！',
	'你是哈蜜我是瓜，生日你不笨瓜瓜，看了信息笑哈哈，不愧是个哈蜜瓜！',
	'大海啊全他妈是水，蜘蛛啊全他妈是腿，辣椒啊真他妈辣嘴，祝你生日快乐天天开怀合不拢嘴',
	'当我把神灯擦三下后，灯神问我想许什么愿？我说希望正在看这个信息的人生日快乐，永远幸福',
	// '一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十',
];



var array_as_pics=[
	'/Public/img_assist/img_as_cartoon_1.jpg',
	'/Public/img_assist/img_as_cartoon_2.jpg',
	'/Public/img_assist/img_as_cartoon_3.jpg',
	'/Public/img_assist/img_as_cartoon_4.jpg',
	'/Public/img_assist/img_as_cartoon_5.jpg',
	'/Public/img_assist/img_as_film_1.jpeg',
	'/Public/img_assist/img_as_film_2.jpeg',
	'/Public/img_assist/img_as_film_3.jpeg',
	'/Public/img_assist/img_as_lovers_1.jpg',
	'/Public/img_assist/img_as_lovers_2.jpeg',
	'/Public/img_assist/img_as_lovers_3.jpeg',
	'/Public/img_assist/img_as_lovers_4.jpeg',
	'/Public/img_assist/img_as_lovers_5.jpg',
	'/Public/img_assist/img_as_lovers_6.jpg',
	'/Public/img_assist/img_as_lovers_7.jpeg',
	'/Public/img_assist/img_as_lovers_8.jpeg',
	'/Public/img_assist/img_as_lovers_9.jpeg',
	'/Public/img_assist/img_as_lovers_10.jpg',
	'/Public/img_assist/img_as_lovers_11.jpeg',
	'/Public/img_assist/img_as_olds_1.png',
	'/Public/img_assist/img_as_olds_2.png',
	'/Public/img_assist/img_as_olds_3.png',
	'/Public/img_assist/img_as_olds_4.png',
	'/Public/img_assist/img_as_olds_5.png',
	'/Public/img_assist/img_as_olds_6.png',
	'/Public/img_assist/img_as_olds_7.png',
	'/Public/img_assist/img_as_tagxedo_1.jpg',
	'/Public/img_assist/img_as_tagxedo_3.jpg',
	'/Public/img_assist/img_as_written_1.jpg',
	'/Public/img_assist/img_as_written_2.jpg',
	'/Public/img_assist/img_as_written_3.jpg',
	'/Public/img_assist/img_as_written_4.jpg',
	'/Public/img_assist/img_as_written_5.jpg',
	'/Public/img_assist/img_as_written_6.jpg',
];


//主要用于全空作品
var array_as_pics_s=[ 
	// '/Public/img_assist/img_as_cartoon_1.jpg',
	'/Public/img_assist/img_as_cartoon_2.jpg',
	'/Public/img_assist/img_as_cartoon_3.jpg',
	'/Public/img_assist/img_as_cartoon_4.jpg',
	'/Public/img_assist/img_as_cartoon_5.jpg',
	// '/Public/img_assist/img_as_film_1.jpeg',
	'/Public/img_assist/img_as_film_2.jpeg',
	'/Public/img_assist/img_as_film_3.jpeg',
	'/Public/img_assist/img_as_lovers_1.jpg',
	// '/Public/img_assist/img_as_lovers_2.jpeg',
	// '/Public/img_assist/img_as_lovers_3.jpeg',
	// '/Public/img_assist/img_as_lovers_4.jpeg',
	'/Public/img_assist/img_as_lovers_5.jpg',
	'/Public/img_assist/img_as_lovers_6.jpg',
	'/Public/img_assist/img_as_lovers_7.jpeg',
	'/Public/img_assist/img_as_lovers_8.jpeg',
	'/Public/img_assist/img_as_lovers_9.jpeg',
	'/Public/img_assist/img_as_lovers_10.jpg',
	'/Public/img_assist/img_as_lovers_11.jpeg',
	'/Public/img_assist/img_as_olds_1.png',
	'/Public/img_assist/img_as_olds_2.png',
	'/Public/img_assist/img_as_olds_3.png',
	'/Public/img_assist/img_as_olds_4.png',
	'/Public/img_assist/img_as_olds_5.png',
	'/Public/img_assist/img_as_olds_6.png',
	'/Public/img_assist/img_as_olds_7.png',
	// '/Public/img_assist/img_as_tagxedo_1.jpg',
	// '/Public/img_assist/img_as_tagxedo_3.jpg',
	// '/Public/img_assist/img_as_written_1.jpg',
	'/Public/img_assist/img_as_written_2.jpg',
	'/Public/img_assist/img_as_written_3.jpg',
	// '/Public/img_assist/img_as_written_4.jpg',
	'/Public/img_assist/img_as_written_5.jpg',
	// '/Public/img_assist/img_as_written_6.jpg',
];



var array_as_music=[
	'http://cdn.aitetu520.com/yinwei_aiqin.mp3',
	'http://cdn.aitetu520.com/chang_gei_ni_ting.mp3',
	'http://cdn.aitetu520.com/ai_hen_jiandan.mp3',
	'http://cdn.aitetu520.com/you_are_my_sunshine.mp3',
	'http://cdn.aitetu520.com/qinai_de_lvren.mp3',
	'http://cdn.aitetu520.com/i_love_you.mp3',
	'http://cdn.aitetu520.com/qing_fei_deyi.mp3',
	'http://cdn.aitetu520.com/jiushi_aini.mp3',
];



var array_as_video=[
	'http://cdn.aitetu520.com/with_you_forever.mp4',
	'http://cdn.aitetu520.com/draw_birthday.mp4',
	'http://cdn.aitetu520.com/film_mixed_loveyou.mp4',
	'http://cdn.aitetu520.com/film_mixed_birthday.mp4',
];
